global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rustygw'
    static_configs:
      - targets: ['localhost:8094']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'rustygw-docker'
    static_configs:
      - targets: ['gateway:8094']
    metrics_path: '/metrics'
    scrape_interval: 5s
